#!/usr/bin/env python3
"""One-off: vendor the Google Fonts v2 uses into ./fonts so renders never hit the network.
Keeps only the latin + latin-ext subsets (latin-ext carries the rupee sign U+20B9)."""
import re, os, urllib.request
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/128 Safari/537.36"
FAMILIES = [
    "Inter:opsz,wght@14..32,100..900",
    "JetBrains+Mono:wght@400..800",
    "Archivo:wdth,wght@62..125,100..900",
    "Caveat+Brush",
    "Caveat:wght@400..700",
]
HERE = os.path.dirname(os.path.abspath(__file__))
out = ["/* generated by fetch_fonts.py: vendored Google Fonts (OFL), latin + latin-ext only */"]
for fam in FAMILIES:
    url = f"https://fonts.googleapis.com/css2?family={fam}&display=block"
    css = urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA})).read().decode()
    for sub, block in re.findall(r"/\* ([\w-]+) \*/\s*(@font-face\s*{[^}]*})", css):
        if sub not in ("latin", "latin-ext"):
            continue
        src = re.search(r"url\((https://[^)]+)\)", block).group(1)
        name = re.search(r"font-family: '([^']+)'", block).group(1).replace(" ", "")
        fn = f"{name}-{sub}-{os.path.basename(src)}"
        path = os.path.join(HERE, "fonts", fn)
        if not os.path.exists(path):
            urllib.request.urlretrieve(src, path)
        out.append(f"/* {sub} */\n" + block.replace(src, f"fonts/{fn}"))
open(os.path.join(HERE, "fonts.css"), "w").write("\n".join(out) + "\n")
print("wrote fonts.css with", len(out) - 1, "faces")
